<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ashwija" ignored="3" name="Default test(failed)(failed)" tests="1" failures="1" timestamp="01 Mar 2018 02:47:22 GMT" time="0.026" errors="0">
  <testcase name="editProduct" time="0.005" classname="qsp.GroupingConceptinTestNG">
    <failure type="java.lang.AssertionError" message="It failed again....">
      <![CDATA[java.lang.AssertionError: It failed again....
	at qsp.GroupingConceptinTestNG.editProduct(GroupingConceptinTestNG.java:43)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- editProduct -->
  <testcase name="getReport" time="0.0" classname="qsp.GroupingConceptinTestNG">
    <ignored/>
  </testcase> <!-- getReport -->
  <testcase name="deleteUser" time="0.0" classname="qsp.GroupingConceptinTestNG">
    <ignored/>
  </testcase> <!-- deleteUser -->
  <testcase name="createUser" time="0.0" classname="qsp.GroupingConceptinTestNG">
    <ignored/>
  </testcase> <!-- createUser -->
</testsuite> <!-- Default test(failed)(failed) -->
